In [1]:
import pandas as pd

In [38]:
#Load in csv
df = pd.read_csv('truliaOuput.csv')

#Get rid of unwanted columns
del df['Unnamed: 0']

In [39]:
#Rename columns to better match description
df.columns = ['Price','SqFt','City','Address','Beds','Baths']
city_state = df['City'].to_list()

#Split up city column into city and state
for item in city_state:
    fixed_col = item.split(',')
    state = fixed_col[-1].strip()
    city = fixed_col[-2].strip()
    try:
        district = fixed_col[-3]
    except IndexError:
        district = 'N/A'

In [40]:
#Add in new columns
df['City'] = city
df['State'] = state
#Re-arrange columns
df = df[['Address','City','State','Price','SqFt','Beds','Baths',]]
df

                   Address    City State       Price         SqFt Beds Baths
0        10310 Bilbrook Pl  Austin    TX    $349,000   1,401 sqft  3bd   3ba
1           1109 Lawson Ln  Austin    TX    $579,000   1,259 sqft  3bd   2ba
2    14412 Ballycastle Trl  Austin    TX    $349,000   2,035 sqft  3bd   3ba
3      10012 Wildflower Ln  Austin    TX    $799,000   2,545 sqft  3bd   2ba
4     12861 Hughes Park Rd  Austin    TX  $5,995,000  13,127 sqft  6bd   7ba
..                     ...     ...   ...         ...          ...  ...   ...
115      7020 Halesboro Dr  Austin    TX    $729,000   3,415 sqft  5bd   4ba
116      2013 Riverview St  Austin    TX    $950,000   2,068 sqft  3bd   3ba
117          511 E Mary St  Austin    TX  $1,195,000   2,276 sqft  3bd   2ba
118       12716 Bismark Dr  Austin    TX    $665,000   3,363 sqft  4bd   4ba
119    4200 Waters Edge Cv  Austin    TX  $7,498,000   7,369 sqft  6bd   9ba

[120 rows x 7 columns]

In [41]:
#Export cleaned csv 
df.to_csv('Cleaned_Trulia.csv')